name: keep-dev-branch-in-sync-with-master
on:
  push:
    branches:
      - master
jobs:
  sync-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: sync dev
        run: sh .github/scripts/sync-dev.sh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
