name: keep-dev-branches-in-sync-with-master
on:
  push:
    branches:
      - master
env:
  PRISMA_TELEMETRY_INFORMATION: "prisma-examples keep-dev-branch-in-sync-with-master.yaml"
jobs:
  sync-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: sync dev
        run: sh .github/scripts/sync.sh dev
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

  sync-patch-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: sync patch-dev
        run: sh .github/scripts/sync.sh patch-dev
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
