name: keep-prisma-dependencies-updated
on:
  push:
    branches-ignore:
      - "**"
  # schedule:
  #   - cron: '*/5 * * * *'
env:
  PRISMA_TELEMETRY_INFORMATION: "prisma-examples keep-prisma-dependencies-updated.yaml"
jobs:
  check-for-update-latest:
    if: github.repository_owner == 'prisma'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: use node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: check update latest
        run: sh .github/scripts/check-for-update.sh latest
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  check-for-update-dev:
    if: github.repository_owner == 'prisma'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: use node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: check update dev
        run: sh .github/scripts/check-for-update.sh dev
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  check-for-update-patch-dev:
    if: github.repository_owner == 'prisma'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: use node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: check update patch-dev
        run: sh .github/scripts/check-for-update.sh patch-dev
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}

  report-to-slack-failure:
    if: github.repository_owner == 'prisma' && failure()
    runs-on: ubuntu-latest
    needs: [check-for-update-latest,  check-for-update-dev,  check-for-update-patch-dev]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          version: 12

      - name: report failure to slack
        run: bash .github/scripts/slack-workflow-status.sh "[keep-prisma-dependencies-updated] check-for-update :x:"
        env:
          SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
