name: sync-alpha
on:
  push:
    branches:
      - master
jobs:
  sync-alpha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: sync alpha
        run: sh .github/scripts/sync-alpha.sh
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
