name: test
on:
  push:
    branches:
      - latest
      - dev
      - patch-dev
  pull_request:
env:
  CI: 1
  PRISMA_TELEMETRY_INFORMATION: 'prisma-examples test.yaml'
  SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
jobs:
  test:
    if: github.repository_owner == 'prisma'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:12-2.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testing
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - '5432:5432'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          version: 12

      - name: test
        run: sh .github/scripts/test-all.sh

      - name: notify-slack
        if: failure() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/patch-dev' || github.ref == 'refs/heads/latest')
        run: bash .github/scripts/slack-workflow-status.sh ":x:"
