name: test
on:
  push:
    branches:
      - latest
      - dev
      - patch-dev
  pull_request:
env:
  CI: 1
  PRISMA_TELEMETRY_INFORMATION: 'prisma-examples test.yaml'
  SLACK_WEBHOOK_URL_FAILING: ${{ secrets.SLACK_WEBHOOK_URL_FAILING }}
jobs:
  projects:
    if: github.repository_owner == 'prisma'
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - name: get list of projects in json array
        id: set-matrix
        run: |
          # list all package.json files (not in node_modules, experimental, .github or deployment-platforms)
          packages=$(find "." -not -path "*/node_modules/*" -not -path "*/experimental/*" -not -path "*/deployment-platforms/*" -not -path "*/.github/*" -not -path "*/.databases/*" -type f -name "package.json")
          # turn each line into json object
          json1=$(echo "$packages" | tr ' ' '\n' | sed 's/.*/{"path": "&" }/')
          # combine objects into json array
          json2=$(echo $json1 | jq -s -c . )
          # and package into wanted json structure
          json3=$(echo "{\"include\":$json2}")
          # set as variable to be used later
          echo "::set-output name=matrix::$json3"
          # output for debugging
          echo $json3

  debug:
    needs: projects
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{needs.projects.outputs.matrix}}"
          echo "${{fromJson(needs.projects.outputs.matrix)}}"

  test:
    needs: projects
    if: github.repository_owner == 'prisma'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.projects.outputs.matrix)}}

    services:
      postgres:
        image: postgis/postgis:12-2.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testing
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - '5432:5432'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          version: 12

      - name: test
        run: sh .github/scripts/test-all.sh ${{ matrix.path }}

      - name: notify-slack
        if: failure() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/patch-dev' || github.ref == 'refs/heads/latest')
        run: bash .github/scripts/slack-workflow-status.sh ":x:"
